version: '3'
services:
  wallet-db:
    image: postgres:12
    environment:
      - POSTGRES_USER=DB_USER
      - POSTGRES_PASSWORD=DB_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - wallet-db-data:/var/lib/pgsql/data
    networks:
      - dao-network

  controller-db:
    image: postgres:12
    environment:
      - POSTGRES_USER=DB_USER
      - POSTGRES_PASSWORD=DB_PASSWORD
    ports:
      - 5433:5432
    volumes:
      - controller-db-data:/var/lib/pgsql/data
      - ./../../scripts/controller-db:/docker-entrypoint-initdb.d
    networks:
      - dao-network
  
  pgadmin:
    image: dpage/pgadmin4:8.0
    container_name: pgadmin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - dao-network

  lifecycle-api:
    build: 
      context: ./../../lifecycle-api/
    ports:
      - 8000:8000
    depends_on:
      - controller-db
    networks:
      - dao-network

  dao-aries-agent:
    image: bcgovimages/aries-cloudagent:py3.9-indy-1.16.0_0.11.0rc2
    command: >
      start  
      --log-level "info"
      --auto-respond-credential-offer
      --auto-accept-invites 
      --auto-accept-requests 
      --auto-ping-connection 
      --admin 0.0.0.0 8038 
      --admin-insecure-mode 
      --genesis-url ${INDY_URL}/genesis 
      -e ${DAO_AGENT_TUNNEL_URL}
      --label dao-aries-agent 
      --seed ${DAO_SEED}
      --tails-server-base-url ${TAILS_SERVER_URL}
      --auto-provision
      --wallet-name dao_agent 
      --wallet-type "askar" 
      --wallet-key "key" 
      --wallet-storage-type "postgres_storage" 
      --wallet-storage-config "{\"url\":\"wallet-db:5432\",\"wallet_scheme\":\"MultiWalletSingleTable\"}"
      --wallet-storage-creds "{\"account\":\"DB_USER\",\"password\":\"DB_PASSWORD\",\"admin_account\":\"DB_USER\",\"admin_password\":\"DB_PASSWORD\"}"
      --webhook-url http://nginx/api/agent-webhook
      -it http 0.0.0.0 8880 -ot http
    ports:
      - "8880:8880"
      - "8038:8038"
    volumes:
      - $PWD:/home/indy/logs
    networks:
      - dao-network
  
  nginx:
    build:
      context: ./../..
    ports:
      - "80:80"
    depends_on:
      - lifecycle-api
    networks:
      - dao-network

  tails-server:
    build:
      context: ./../../indy-tails-server/
      dockerfile: ./../../indy-tails-server/docker/Dockerfile.tails-server
    ports:
      - 6543:6543
    networks:
      - dao-network
    command: >
      tails-server
        --host 0.0.0.0
        --port 6543
        --storage-path $STORAGE_PATH
        --log-level $LOG_LEVEL
        
volumes:
  wallet-db-data:
  controller-db-data:

networks:
  dao-network:
    name: dao-network
    